apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: fd5oy6jfw-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fd5oy6jfw-nodejs 
  name: fd5oy6jfw-nodejs
spec:
  port:
    targetPort: 3001 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: fd5oy6jfw-nodejs
    weight: 100 
